app1/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:title>/', views.blog_content, name="blog_content"),
    path('add-blog', views.blog_form, name="blog_form"),
    path('<str:title>/like/', views.blog_like, name="like"),
]

project1ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('blogs/', include('app2.urls')),
    path('about/', include('app3.urls')),
    path('recommendation/', include('app4.urls')),
]

app2/models.py
from django.db import models

# Create your models here.
class Visitor(models.Model):
    name = models.CharField(default="Anonymous", max_length=50, blank=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    message = models.CharField(max_length=500)
    commenter = models.ForeignKey(Visitor, related_name="visitor_comment", on_delete= models.SET_NULL, null=True, blank=True)
    date_created = models.DateField(auto_now=True)

    def __str__(self):
        return "{} - {}".format(self.commenter, self.message)

class Blog(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    name = models.CharField(default="Anonymous", max_length=50, blank=True)
    likes = models.ManyToManyField(Visitor, related_name="blog_likes", blank=True)
    comment = models.ManyToManyField(Comment, blank=True)

    def __str__(self):
        return self.title

    def blogTotalLikes(self):
        return self.likes.all().count()

app2/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Your blog's title"}),
            'content' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Your story..."}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

        widgets = {
            'message' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Your comment..."}),
        }

app2/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.


def index(request):
	blogs = Blog.objects.all()
	return render(request, 'app2/blog.html', {'blogs': blogs})

def blog_form(request):
	form = BlogForm(request.POST or None)
	if request.method == "POST":
		if form.is_valid():
			dataBlog = form.cleaned_data
			if request.COOKIES.get('name') == None:
				newBlog = Blog(title=dataBlog['title'], content=dataBlog['content'], name="Anonymous")
			else:
				newBlog = Blog(title=dataBlog['title'], content=dataBlog['content'], name=request.COOKIES.get('name'))
			newBlog.save()
			return redirect('/blogs')

	return render(request, 'app2/blog_form.html', {"form":form, 'name': request.COOKIES.get('name')})

def blog_content(request, title):
	blogs = Blog.objects.all()

	if blogs.count() != 0: 
		blog = Blog.objects.get(title=title)
		form = BlogForm()
		comment_form = CommentForm()

		if request.method == "POST":
			comment_form = CommentForm(request.POST)
			if comment_form.is_valid():
				dataComment = comment_form.cleaned_data
				msg = dataComment['message']
				if request.COOKIES.get('name') == None:
					prsn = "Anonymous"
				else:
					prsn = request.COOKIES.get('name')
				blog.comment.create(message=msg, commenter=Visitor.objects.get(name=request.COOKIES.get('name')))
				blog.save()
				return redirect('/blogs/')
		
		context = {'blog': blog, "form": form, 'cform': comment_form}

		return render(request, 'app2/blog_content.html', context)

	else:
		return redirect('/blogs/')

# mekanisme likenya masih flaw, dengan problem berikut:
# setelah di-like, pas coba di refresh, tombol likenya ke reset (jadi kek belum di-like) dan counter like nya ke reset
# setelah di-like, pas pengen ngunjungin blog-nya yang udah di like, tombol likenya ke reset tapi counter like nya kaga ke reset

def blog_like(request, title):	
	blog = Blog.objects.get(title=title)
	form = BlogForm()
	person = request.COOKIES.get('name')
	comment_form = CommentForm()

	if person == None:
		visitor = Visitor(name="Anonymous")
		visitor.save()

	else:
		visitor, created = Visitor.objects.get_or_create(name=person)

		
	context={
		'visitor' : visitor,
		'liked' : False,
		'blog' : blog,
		'form' : form,
		'cform' : comment_form
	}

	if request.method == "POST":
		# setelah di like, rencananya form blog masih bisa dipake utk buat blog dan form comment masih bisa utk ngisi comment
		# gua coba terapin hal diatas dengan code "blog_content(request, title)", tapi kayaknya masih ngaco
		# karena setiap kali gw refresh setelah gua nambah comment, comment yang sama ketambah lagi wkwkw (apa emg kek gitu cara kerjanya wkwk)
		# mohon bantuannya
		blog_content(request, title) 
		if blog.likes.filter(name=visitor).exists():
			blog.likes.remove(visitor)
			context['liked'] = False
		else:
			blog.likes.add(visitor)
			context['liked'] = True
			
		blog.save()

	return render(request, 'app2/blog_content.html', context)

app2/templates/app2/blog.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Blogs
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_blog.css' %}">
{% endblock %}


{% block content %}
<div class="container-lg intros">
    <div class="intro">
        <img src="{% static 'admin/img/blog 1.svg' %}" alt="blog-icon">
        <h1 class="intro-title">Blogs.</h1>
        <p class="intro-subtitle">things you might want to know <br>about <span>quarantine</span> and such.</p>
    </div>
</div>

{% if not blogs %}
<div class="container-lg blog-warning">
    <div class="blog-warn">
        <h1>There are <span class="bold-red">no blogs</span> to be found so far. Add yours!</h1>
        <a class="btn btn-lg" href="{% url 'blogs:blog_form' %}" role="button">Add</a>
    </div>
</div>

{% else %}
<div class="container-fl blog-preview">
    <div class="row">
        {% for blog in blogs %}
        <div class="col-lg-4 d-flex align-items-stretch">
            <div class="card h-100">
                <h3 class="card-title h-100">{{blog.title}}</h3>
                <p class="card-text h-100">{{blog.content|truncatewords:15}}</p>
                <div class="button-more">
                    <a class="btn btn-lg" href="{% url 'blogs:blog_content' blog.title %}" role="button">More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% endblock %}

app2/templates/app2/blog_content.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Blogs
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_blog.css' %}">
{% endblock %}


{% block content %}
<div class="container-lg blog-content">
    <div class="blog-about">
        <div class="blog-info">
            <h1 class="title">{{blog.title}}</h1>
            <h2 class="subtitle">By:<br>{{blog.name}}</h2>
        </div>
    </div>
    <p class="long-par">{{blog.content}}</p>
    
    <div class="blog-likes">
        <form action="{% url 'blogs:like' blog.title %}" method="POST">
            {% csrf_token %}
            {% if liked %}
            <input type="image" src="{% static 'admin/img/heart-like.svg' %}" alt="Unlike">
            {% else %}
            <input type="image" src="{% static 'admin/img/heart-unlike.svg' %}" alt="Like">
            {% endif %}
        </form>
        <h3 class="like-counter">{{blog.blogTotalLikes}}</h3>
    </div>
    
</div>

<div class="container-lg blog-comment">
    <div class="list-comment">
        <h1><span class="bold-red">comments</span></h1>
        
        {% for com in blog.comment.all %}
        <div class="comment">
            <h3><span class="bold-red">{{com.commenter}}</span> - ({{com.date_created}})</h3>
            <p class="long-par">{{com.message}}</p>
        </div>
        {% endfor %}
        
    </div>
    <div class="comment-form">
        {% if blog.comment.all %}
        <h1>Add your comment <span class="bold-red">here!</span></h1>
        {% else %}
        <h1>There are <span class="bold-red">no comments</span> so far. Add <span class="bold-red">yours!</span></h1>
        {% endif %}
        <div class="form-group">
            <form action="#" method="post">
            {% csrf_token %}
            {{cform}}
            <div class="send-btn">
                <input class="btn btn-dark btn-lg but-add" type="submit" value="Add comment">
            </div>
            </form>
        </div>
    </div>
</div>

<div class="container-lg blog-form">
    <h1>This is <span class="bold-red">our story,</span> tell us about <span class="bold-red">yours.</span></h1>
    <div class="form-group">
        <form action="{% url 'blogs:blog_form' %}" method="post">
        {% csrf_token %}
        {{form}}
        <div class="send-btn">
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Send">
        </div>
        </form>
    </div>
</div>
{% endblock %}

app2/templates/app2/blog_form.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Blogs
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_blog.css' %}">
{% endblock %}


{% block content %}
<div class="container-lg blog-form polos">
    {% if not name %}
    <h1>Hi, Tell us about <span class="bold-red">your story.</span></h1>
    {% else %}
    <h1>Hi {{name}}, Tell us about <span class="bold-red">your story.</span></h1>
    {% endif %}
    <div class="form-group">
        <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <div class="send-btn">
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Send">
        </div>
        </form>
    </div>
</div>
{% endblock %}