app1/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

app4/urls.py
from django.urls import path
from . import views

app_name = 'recommendation'

urlpatterns = [
    path('', views.index, name="index"),
    path('games/', views.games, name="games"),
    path('movies/', views.movies, name="movies"),
    path('music/', views.music, name="music"),
    path('podcast/', views.podcast, name="podcast"),
    path('<str:model>/poll/', views.poll, name="poll"),
]

project1ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('blogs/', include('app2.urls')),
    path('about/', include('app3.urls')),
    path('recommendation/', include('app4.urls')),
]

app4/models.py
from django.db import models

# Create your models here.

class Games(models.Model):
	name = models.CharField(max_length=120, unique=True)
	desc = models.TextField(blank=True, null=True)
	poll = models.PositiveIntegerField(default=0)
	avg = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "{} - {}".format(self.id, self.name)

	def Poll(self):
		self.poll += 1
		self.save()


class Music(models.Model):
	name = models.CharField(max_length=120, unique=True)
	desc = models.TextField(blank=True, null=True)
	poll = models.PositiveIntegerField(default=0)
	avg = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "{} - {}".format(self.id, self.name)

	def Poll(self):
		self.poll += 1
		self.save()


class Movies(models.Model):
	name = models.CharField(max_length=120, unique=True)
	desc = models.TextField(blank=True, null=True)
	poll = models.PositiveIntegerField(default=0)
	avg = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "{} - {}".format(self.id, self.name)

	def Poll(self):
		self.poll += 1
		self.save()


class Podcast(models.Model):
	name = models.CharField(max_length=120, unique=True)
	desc = models.TextField(blank=True, null=True)
	poll = models.PositiveIntegerField(default=0)
	avg = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "{} - {}".format(self.id, self.name)

	def Poll(self):
		self.poll += 1
		self.save()

app4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
# Create your views here.


def index(request):
	return render(request, "app4/rekomendasi.html")

# def model(request, model):
# 	objects = 0
# 	templates = ''
# 	if model == "Games":
# 		objects = Games.objects.all()
# 		templates = 'app/games.html'
# 	elif model == "Movies":
# 		objects = Movies.objects.all()
# 		templates = 'app/movies.html'
# 	elif model == "Music":
# 		objects = Music.objects.all()
# 		templates = 'app/musics.html'
# 	elif model == "Podcast":
# 		objects = Podcast.objects.all()
# 		templates = 'app/podcast.html'

# 	total = 0
# 	for o in objects:
# 		total += o.poll

# 	for o in objects:
# 		o.avg = round(o.poll / total * 100)
# 		o.save()

# 	data={
# 		'object':games,
# 		'model' : 'games',
# 		'cek' : request.COOKIES.get('poll_games'),
# 		'name': request.COOKIES.get('name'),

def games(request):
	games = Games.objects.all().order_by('id')
	total = 0
	for g in games:
		total += g.poll

	for g in games:
		try:
			g.avg = round(g.poll / total * 100)
		except:
			g.avg = 0
		g.save()

	data={
		'object':games,
		'model' : 'games',
		'cek' : request.COOKIES.get('poll_games'),
		'name': request.COOKIES.get('name'),
	}

	return render(request, "app4/games.html", data)

def music(request):
	music = Music.objects.all().order_by('id')
	total = 0
	for m in music:
		total += m.poll

	for m in music:
		try:
			m.avg = round(m.poll / total * 100)
		except:
			m.avg = 0
		m.save()


	data={
		'object':music,
		'model' : 'music',
		'cek' : request.COOKIES.get('poll_music'),
		'name': request.COOKIES.get('name'),
	}

	return render(request, "app4/musics.html", data)

def movies(request):
	movies = Movies.objects.all().order_by('id')
	total = 0
	for m in movies:
		total += m.poll

	for m in movies:
		try:
			m.avg = round(m.poll / total * 100)
		except:
			m.avg = 0
		m.save()


	data={
		'object':movies,
		'model' : 'movies',
		'cek' : request.COOKIES.get('poll_movies'),
		'name': request.COOKIES.get('name'),
	}

	return render(request, "app4/movies.html", data)	

def podcast(request):
	podcast = Podcast.objects.all().order_by('id')
	total = 0
	print(podcast)
	for p in podcast:
		total += p.poll

	for p in podcast:
		try:
			p.avg = round(p.poll / total * 100)
		except:
			p.avg = 0
		p.save()

	data={
		'object':podcast,
		'model' : 'podcast',
		'cek' : request.COOKIES.get('poll_podcast'),
		'name': request.COOKIES.get('name'),
	}

	return render(request, "app4/podcast.html", data)

def poll(request, model):
	if model == 'games':
		id = request.POST.get('item')
		game = Games.objects.get(id=id)
		game.Poll()
		r = redirect("/recommendation/games/")
		r.set_cookie('poll_games', True)
		return r

	if model == 'movies':
		id = request.POST.get('item')
		movie = Movies.objects.get(id=id)
		movie.Poll()
		r = redirect("/recommendation/movies/")
		r.set_cookie('poll_movies', True)
		return r

	if model == 'music':
		id = request.POST.get('item')
		music = Music.objects.get(id=id)
		music.Poll()
		r = redirect("/recommendation/music/")
		r.set_cookie('poll_music', True)
		return r

	if model == 'podcast':
		id = request.POST.get('item')
		podcast = Podcast.objects.get(id=id)
		podcast.Poll()
		r = redirect("/recommendation/podcast/")
		r.set_cookie('poll_podcast', True)
		return r

app4/templates/app4/games.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Games
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_games.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_poll.css' %}">
{% endblock %}

{% block content %}
<div class="container-lg games">
    <div class="games-about">
        <img src="{% static 'admin/img/Console (1).svg' %}" alt="console-icon">
        <div class="games-desc">
            <h1 class="title">g<span class="red">am</span>e<span class="red">s</span></h1>
            <p class="desc">Quarantine may sucks, but games keeps on giving! 
                Many new games comes with <span class="red">multiplayer</span> so that you can have <span class="red">fun together</span>, 
                even when you’re not directly together.</p>
        </div>
    </div>
</div>

<div class="container-lg games-benefit">
    <div class="benefit">
        <h1 id="benefits">#bene<br><span class="red">fits</span>.</h1>
        <div class="list-benefit">
            <ul>
                <div class="list-bulet">
                    <li><a href="/">reduce boringness</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">may develop new skills related to games</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">get close to friends</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">stress-reliever</a></li>
                </div>
            </ul>
        </div>
    </div>
</div>

<div class="container-lg short-msg">
    <h1 class="msg-title"><span class="red">game</span> on!</h1>
</div>

<div class="container-fl showcase">
    <div class="case">
        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/image-6.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">Fall Guys<br>(2020)</h1>
                <p class="img__description">Fall Guys is a massively multiplayer party game with up to 60 players online 
                    in a free-for-all struggle through round after round of escalating chaos until one victor remains!</p>
                <h1 class="img__title">Battle Royale, Multiplayer</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/image-7.jpg' %}" />
            <div class="img__description_layer">
              <h1 class="img__title">Among Us<br>(2018)</h1>
                <p class="img__description">Join your crewmates in a multiplayer game of teamwork and betrayal as you attempt to hold your spaceship together and return back to civilization. 
                    But beware...as there may be an alien impostor aboard!</p>
                <h1 class="img__title">Betrayal, Teamwork, Multiplayer</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/image-8.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">Rocket League<br>(2015)</h1>
                <p class="img__description">Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition.</p>
                <h1 class="img__title">Sports, Multiplayer</h1>
            </div>
        </div>
    </div>
</div>

<div class="container-lg games-sources">
    <h1 id="sources">#sour<br><span class="red">ces</span>.</h1>
    <div class="list-sources">
        <img src="{% static 'admin/img/steam-logo 1.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/playstore 1.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/image 10.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app-store 1.svg' %}" alt="console-icon">
    </div>
</div>

<div class="container-fl poll-msg">
    <div class="p-msg">
        <h1 class="msg-title">Vote our Recommendation!</h1>
        <p>#now_or_never</p>
    </div>
</div>

<div class="container-fl poll">
    <div class="poll-title">
        <h1><span class="red">G</span>am<span class="red">e</span>s</h1>
        <img src="{% static 'admin/img/Console-sm.svg' %}" src="">
    </div>
    {% include 'app4/poll.html' %}
</div>

{% endblock %}

app4/templates/app4/movies.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Games
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_movies.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_poll.css' %}">
{% endblock %}

{% block content %}
<div class="container-lg movies">
    <div class="movies-about">
        <img src="{% static 'admin/img/movies.svg' %}" alt="console-icon">
        <div class="movies-desc">
            <h1 class="title"><span class="red">mov</span>i<span class="red">e</span>s</h1>
            {% comment %} <p class="desc">Quarantine may sucks, but games keeps on giving! 
                Many new games comes with <span class="red">multiplayer</span> so that you can have <span class="red">fun together</span>, 
                even when you’re not directly together.</p> {% endcomment %}
            <p class="desc">While on quarantine, you might be bored cause 
            doing nothing. <span class="red">STOP</span> wasting your time, watch movies and get 
            <span class="red">5 benefits</span> from doing so! </p>
        </div>
    </div>
</div>

<div class="container-lg movies-benefit">
    <div class="benefit">
        <h1 id="benefits">#bene<br><span class="red">fits</span>.</h1>
        <div class="list-benefit">
            <ul>
                <div class="list-bulet">
                    <li><a href="/">help us learn through the actors stories</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">can drive social change</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">help us process difficult life lessons</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">(are) still a social experience</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">help us appreciate art</a></li>
                </div>
            </ul>
        </div>
    </div>
</div>

<div class="container-lg short-msg">
    {% comment %} <h1 class="msg-title"><span class="red">game</span> on!</h1> {% endcomment %}
    <h1 class="msg-title"><span class="red">suit</span> your <span class="red">taste.</span></br>
    <span class="red">find</span> your <span class="red">happiness!</span></h1>
</div>

<div class="container-fl showcase">
    <div class="case">
        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/shining.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">The SHINING<br>(1980)</h1>
                <p class="img__description">A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.</p>
                <h1 class="img__title">Drama, Horror</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/once.jpg' %}" />
            <div class="img__description_layer">
              <h1 class="img__title">Once Upon A Time In Hollywood<br>(2019)</h1>
                <p class="img__description">A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.</p>
                <h1 class="img__title">Comedy, Drama</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/lalaland.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">La La LAND<br>(2016)</h1>
                <p class="img__description">While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.</p>
                <h1 class="img__title">Romance, Drama, Music</h1>
            </div>
        </div>
    </div>
</div>

<div class="container-fl showcase">
    <div class="case">
        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/avengers.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">AVENGERS<br>(2002 - 2019)</h1>
                <p class="img__description">Marvel’s SuperHero series, you can watch each series of the SuperHero so you can know more about each one of them, and watch Avengers if you to see their chemistry!<strong> GO BINGE-WATCH! </strong></p>
                <h1 class="img__title">Action, Adventure, Sci-Fi</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/harry.jpg' %}" />
            <div class="img__description_layer">
              <h1 class="img__title">Harry Potter<br>(2001 - 2011)</h1>
                <p class="img__description">Harry Potter and the Philosopher's Stone is a 2001 fantasy film directed by Chris Columbus and distributed by Warner Bros. Pictures, based on J. K. Rowling's 1997 novel of the same name.<strong> GO BINGE-WATCH!</strong></p>
                <h1 class="img__title">Adventure, Family, Fantasy</h1>
            </div>
        </div>

        <div class="img__wrap">
            <img class="img__img" src="{% static 'admin/img/joker.jpg' %}" />
            <div class="img__description_layer">
                <h1 class="img__title">JOKER<br>(2019)</h1>
                <p class="img__description">In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.</p>
                <h1 class="img__title">Crime, Drama, Thriller</h1>
            </div>
        </div>
    </div>
</div>

<div class="container-lg movies-sources">
    <h1 id="sources">#sour<br><span class="red">ces</span>.</h1>
    <div class="list-sources">
        <img src="{% static 'admin/img/netflix 1.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/hbo 1.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app3/app4/source_youtube.svg' %}" alt="console-icon">
    </div>
</div>

<div class="container-fl poll-msg">
    <div class="p-msg">
        <h1 class="msg-title">Vote our Recommendation!</h1>
        <p>#now_or_never</p>
    </div>
</div>

<div class="container-fl poll">
    <div class="poll-title">
        <h1><span class="red">Mov</span>i<span class="red">e</span>s</h1>
        <img src="{% static 'admin/img/Movies-sm.svg' %}" src="">
    </div>
    {% include 'app4/poll.html' %}
</div>

{% endblock %}


app4/templates/app4/musics.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Music
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_music.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_poll.css' %}">
{% endblock %}

{% block content %}
<div class="container-lg musics">
    <div class="musics-about">
        <img src="{% static 'admin/img/app3/app4/music_logo.svg' %}" alt="console-icon">
        <div class="musics-desc">
            <h1 class="title"><span class="red">M</span>us<span class="red">ic</span></h1>
            <p class="desc">Who doesn't <span class="red">listen to music</span> nowadays?
                Many people listen to music to keep up the <span class="red">productivity.</span>
                This list of music may do the trick for you!</p>
        </div>
    </div>
</div>

<div class="container-lg musics-benefit">
    <div class="benefit">
        <h1 id="benefits">#bene<br><span class="red">fits</span>.</h1>
        <div class="list-benefit">
            <ul>
                <div class="list-bulet">
                    <li><a href="/">can boost up our productivity</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">to help calm ourselves</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">makes us happier</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">increase our verbal intelligence</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">reduce depression</a></li>
                </div>
            </ul>
        </div>
    </div>
</div>

<div class="container-lg short-msg">
    <h1 class="msg-title"><span class="red">Music</span> can change the world because it can <span class="red">change people.</span></h1>
</div>

<div class="container-fl showcase">
    <div class="case-wrapper">
        <div class="case">
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_1.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">All the kids are depressed</h1>
                    <h4 class="img__description">Jeremy Zucker</h4>
                    <h3 class="img__title">Pop</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_2.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Corduroy Dreams</h1>
                    <h4 class="img__description">Rex Orange County</h4>
                    <h3 class="img__title">Indie Pop/Alternative</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_3.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Boom</h1>
                    <h4 class="img__description">NCT Dream.</h4>
                    <h3 class="img__title">K-Pop</h3>
                </div>
            </div>
        </div>
        <div class="case" id="second-case">
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_4.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Jaran Goyang</h1>
                    <h4 class="img__description">Nella Kharisma</h4>
                    <h3 class="img__title">Indonesian Pop</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_5.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Before you Go</h1>
                    <h4 class="img__description">Lewis Capaldi</h4>
                    <h3 class="img__title">Indie Pop/Alternative</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/music_6.jpg' %}" />
                <div class="img__description_layer">
                    <h class="img__title">Lemon</h1>
                    <h4 class="img__description">Kenshi Yonezu</h4>
                    <h3 class="img__title">J-Pop</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-lg musics-sources">
    <h1 id="sources">#sour<br><span class="red">ces</span>.</h1>
    <div class="list-sources">
        <img src="{% static 'admin/img/app3/app4/source_spotify.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app3/app4/source_youtube.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app3/app4/source_soundcloud.svg' %}" alt="console-icon">
    </div>
</div>

<div class="container-fl poll-msg">
    <div class="p-msg">
        <h1 class="msg-title">Vote our Recommendation!</h1>
        <p>#now_or_never</p>
    </div>
</div>

<div class="container-fl poll">
    <div class="poll-title">
        <h1>M<span class="red">us</span>i<span class="red">c</span>s</h1>
        <img src="{% static 'admin/img/Music-sm.svg' %}" style="max-width: 15%;" src="">
    </div>
    {% include 'app4/poll.html' %}
</div>

{% endblock %}

app4/templates/app4/podcast.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Podcast
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_podcast.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_poll.css' %}">
{% endblock %}

{% block content %}
<div class="container-lg podcast">
    <div class="podcast-about">
        <img src="{% static 'admin/img/app3/app4/podcast_logo.svg' %}" alt="console-icon">
        <div class="podcast-desc">
            <h1 class="title">POD<span class="red">CAST</span></span></h1>
            <p class="desc">In these times, there are many podcast comes with <span class="red">interesting talks.</span>
                 In fact, this podcast thingy became <span class="red">popular.</span></p>
        </div>
    </div>
</div>

<div class="container-lg podcast-benefit">
    <div class="benefit">
        <h1 id="benefits">#bene<br><span class="red">fits</span>.</h1>
        <div class="list-benefit">
            <ul>
                <div class="list-bulet">
                    <li><a href="/">discovering new things</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">beneficial free times</a></li>
                </div>
                <div class="list-bulet">
                    <li><a href="/">learn from other experiences</a></li>
                </div>
            </ul>
        </div>
    </div>
</div>

<div class="container-lg short-msg">
    <h1 class="msg-title">we're <span class="red">going</span> real <span class="red">deep.</span></h1>
</div>

<div class="container-fl showcase">
    <div class="case-wrapper">
        <div class="case">
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/pd_1.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">PORD</h1>
                    <h4 class="img__description">Raditya Dika</h4>
                    <h3 class="img__title">Society & Culture, Educational</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/pd_2.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Menjadi Manusia,</h1>
                    <h4 class="img__description">Doni Febriando</h4>
                    <h3 class="img__title">Lifestyle and Health</h3>
                </div>
            </div>
        </div>
        <div class="case" id="second-case">
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/pd_3.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">Do you see what I see</h1>
                    <h4 class="img__description">Rizki Ardi Nugroho</h4>
                    <h3 class="img__title">Stories, Horor</h3>
                </div>
            </div>
            <div class="img__wrap">
                <img class="img__img" src="{% static 'admin/img/app3/app4/pd_4.jpg' %}" />
                <div class="img__description_layer">
                    <h1 class="img__title">#NgobrolinStartup</h1>
                    <h4 class="img__description">DailySocial</h4>
                    <h3 class="img__title">Bussiness and Tech</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-lg podcast-sources">
    <h1 id="sources">#sour<br><span class="red">ces</span>.</h1>
    <div class="list-sources">
        <img src="{% static 'admin/img/app3/app4/source_spotify.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app3/app4/source_google.svg' %}" alt="console-icon">
        <img src="{% static 'admin/img/app3/app4/source_soundcloud.svg' %}" alt="console-icon">
    </div>
</div>

<div class="container-fl poll-msg">
    <div class="p-msg">
        <h1 class="msg-title">Vote our Recommendation!</h1>
        <p>#now_or_never</p>
    </div>
</div>

<div class="container-fl poll">
    <div class="poll-title">
        <h1><span class="red">Pod</span>cast</h1>
        <img src="{% static 'admin/img/Podcast-sm.svg' %}" src="">
    </div>
    {% include 'app4/poll.html' %}
</div>

{% endblock %}

app4/templates/app4/poll.html
{% if not cek %}
<div class="container">
	{% if not name %}
	<h2> Hi there, let's vote our recommendation.</h2>
	{% else %}
	<h2> Hi {{name}}, let's vote our recommendation.</h2>
	{% endif %}
	<form action="poll/#result-poll" method="post">
	{% csrf_token %}
	<div class="poll-wrapper">
		{% for m in object %}
		<div class="poll-item">
			<input type="radio" id="{{m.name}}" name="item" value="{{m.id}}">
  			<label for="{{m.name}}"><span><span></span></span>{{m.name}}</label><br>
		</div>
	{% endfor %}
	</div>
	<div class="input-btn">
		<input type="submit"/>
	</div>
	</form>
</div>
{% else %}
<div id="result-poll" class="container">
	{% if not name %}
	<h2> Thanks for your votes! And let us know your name, fill it in <a href="{% url 'home:index' %}"> Home</a></h2>
	{% else %}
	<h2> Thanks {{name}} for your votes!</h2>
	{% endif %}
	<div class="result-poll-wrapper">
		{% for m in object %}
		<div class="result-poll-item">
			<h3 class="result-poll-label">{{m.name}}<!-- poll : {{m.poll}}--></h3>
			<div class="progress">
				<div class="progress-bar" role="progressbar" style="width: {{m.avg}}%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">{{m.avg}}%</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endif %}

app4/templates/app4/rekomendasi.html
{% extends 'base_nofooter.html' %}

{% load static %}
{% block title %}
Recommendation
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_rekomendasi.css' %}">
{% endblock %}


{% block content %}
<div class="container-lg intros">
    <div class="intro">
        <img src="{% static 'admin/img/checklist 1.svg' %}" alt="recomm-icon">
        <div class="long-title">
            <h1 class="intro-title">Recommendation.</h1>
        </div>
        <p class="intro-subtitle">there are a <span>lot of things</span> to do,</p>
        <ul class="list-recomm">
            <li><a href="{% url 'recommendation:music' %}">music</a></li>
            <li><a href="{% url 'recommendation:movies' %}">movies</a></li>
            <li><a href="{% url 'recommendation:games' %}">games</a></li>
            <li><a href="{% url 'recommendation:podcast' %}">podcast</a></li>
        </ul>
        <div class="arrow">
            <img src="{% static 'admin/img/icon arrow.svg' %}" alt="arrow-icon">
        </div>
    </div>
</div>

{% endblock %}