app1/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:title>/', views.blog_content, name="blog_content"),
    path('add-blog', views.blog_form, name="blog_form"),
    path('<str:title>/like/', views.blog_like, name="like"),
]

app3/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.index, name="index"),
]

app4/urls.py
from django.urls import path
from . import views

app_name = 'recommendation'

urlpatterns = [
    path('', views.index, name="index"),
    path('games/', views.games, name="games"),
    path('movies/', views.movies, name="movies"),
    path('music/', views.music, name="music"),
    path('podcast/', views.podcast, name="podcast"),
    path('<str:model>/poll/', views.poll, name="poll"),
]

project1ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('blogs/', include('app2.urls')),
    path('about/', include('app3.urls')),
    path('recommendation/', include('app4.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}

    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm py-3">
            <div class="container">
                <a class="navbar-brand" href="/"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'home:index' %}">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'about:index' %}">about</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'blogs:index' %}">blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'recommendation:index' %}">recommendation</a>
                        </li>
                        <!--<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'recommendation:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            recommendation
                        </a>-->
                        
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}


<!-- Footer -->

    <footer class="page-footer font-small">
      <!-- Copyright -->
      <div class="footer-copyright text-right py-3">
        <div class="footer-content">
            <div class="top" id="backtop">
                <a id="backtop_logo" href="#" onclick="scrollTopAnimated()">
                    <img src="{% static 'admin/img/icon (1).svg' %}" alt="icon-arrow">
                </a>
                <a id="backtop_text" href="#" onclick="scrollTopAnimated()"><p>back to top</p></a>
            </div>
            
            <p>© Copyright All right reserved |<a> Design by WETZ</a></p>
        </div>
        
      </div>    
      <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"> </script> 
    <script type="text/javascript"> 
        function scrollTopAnimated() { 
            $("html, body").animate( 
                { scrollTop: "0" }, 700); 
        } 
    </script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/base_kosong.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}
    
    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/base_nofooter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}

    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm py-3">
            <div class="container">
                <a class="navbar-brand" href="/"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'home:index' %}">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'about:index' %}">about</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'blogs:index' %}">blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'recommendation:index' %}">recommendation</a>
                        </li>
                        <!--<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'recommendation:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            recommendation
                        </a>-->
                        
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/home.html
{% extends 'base_kosong.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/homep.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/homepage_respons.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebarnews.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebar_responsives.css' %}">
{% endblock css %}


{% block title %}Homepage{% endblock title %}

{% block content %}

{% if not name %}
<div class="container">
	<div class = "wrap">
		<div class="form-form-group col-md-12 title">
			<h1 span class="well">WELCOME!</h1>	
			<h2 span class="what">What's your name?</h2>
		</div>

		<form method="post">
		{% csrf_token %}
			<div class="form-row">
				<div class="form-group col-md-12">
				{{form.name}}
				</div>
			</div>
		<button type="submit" class="btn">Submit</button>
		</form>
	</div>
</div>


{% else %}
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
<!-- The sidebar -->
{% comment %} <div class="row home">
<div class="sidebar"> {% endcomment %}
	<a href="{% url 'about:index' %}" class="icon">
		<img src="{% static 'admin/img/Group_home.svg' %}" alt="console-icon" >
	</a>
	<a href="{% url 'blogs:index' %}" class="icon">
		<img src="{% static 'admin/img/blog 1_home.svg' %}" alt="console-icon" >
	</a>
	<a href="{% url 'recommendation:index' %}" class="icon">
		<img src="{% static 'admin/img/checklist 1_home.svg' %}" alt="console-icon" >
	</a>
</div>

<div id="main">
  	
<!-- Page content -->
		<div class="container-fluid home ">
			<button class="openbtn" onclick="openNav()">>>></button> 
			<div class="row rapi">
				<div class="col col-lg-7">
					<div class="d-flex h-100">
						<div class="text-left align-self-center pads">
							<h5 class="red first"> Hello, {{name}}. </h5>
							<h2 class="yellow second"> What to do during, </h2>
							<h1 class="wellcom red left third"> QUARAN </h1>
							<h1 class="wellcom red left"> TINE? </h1>
							<p class="descrip yellow"> Got nothing to do at home? You are stuck on your mind? Got bored during your quarantine? <strong class="red" > Explore US! </strong> and we'll show you something fun</p>
						</div>
					</div>
				</div>
				<div class="col col-lg-5 p-0 m-0">
					<img src="{% static 'admin/img/gify.gif' %}" class="dekstop">
				</div> 
			</div>
		</div>
</div>

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "150px";
  document.getElementById("main").style.marginLeft = "150px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>  
   
{% endif %}

{% endblock content %}

{% block js %}
    
{% endblock js %}

templates/home2.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/homepage.css' %}">
{% endblock css %}


{% block title %}Homepage{% endblock title %}

{% block content %}

{% if not cek %}
<div class="container">
	<div class="a">
		<div class="form-form-group col-md-12 title">
			<h1 span class="well">WELCOME!</h1>	
			<h2 span class="what">What's your name?</h2>
		</div>

		<form method="post">
		{% csrf_token %}
			<div class="form-row">
				<div class="form-group col-md-12">
				{{form.name}}
				</div>
			</div>
		<button type="submit" class="btn">Submit</button>
		</form>
	</div>
</div>
{% else %}
<div class="container">
	<h3>Hi {{name}}</h3>
</div>
{% endif %}

{% endblock content %}

{% block js %}

    
{% endblock js %}